apps:
  - name: ccu_app
    script: serve
    instances: 1
    exec_mode: cluster
    env:
      PM2_SERVE_PATH: ./build
      PM2_SERVE_PORT: 4001
      PM2_SERVE_SPA: true
      NODE_ENV: production
deploy:
  production:
    user: psante
    host: 
      -
        host : 160.120.185.111
        port : '2226'
    repo: https://github.com/dykoffi/ccu_app.git
    ref: origin/master
    path: /home/psante/Apps/test/ccu/app
    post-deploy: yarn install ; yarn build ; pm2 startOrReload build.yaml ; pm2 save
