apps:
  - name: ccu_app
    script: serve
    instances: 1
    exec_mode: cluster
    env:
      PM2_SERVE_PATH: ./build
      PM2_SERVE_PORT: 4001
      PM2_SERVE_SPA: true
      NODE_ENV: production
deploy:
  production:
    user: psante
    host:
      - host: 160.120.185.111
        port: "2226"
    ref: origin/master
    repo: git@github.com:ccu_app.git
    path: /home/psante/Apps/test/ccu/app
    ssh_options: ["StrictHostKeyChecking=no", "PasswordAuthentication=no"]
    post-deploy: yarn install ; yarn build ; pm2 startOrReload build.yaml ; pm2 save
