apps:
  - name: ccu_app
    script: production.js
    instances: 3
    exec_mode: cluster
deploy:
  production:
    user: psante
    host:
      - host: 160.120.185.111
        port: "2226"
    ref: origin/main
    repo: git@github.com:dykoffi/ccu_app.git
    path: /home/psante/Apps/test/ccu/app
    post-deploy: yarn install ; yarn build ; pm2 startOrReload build.yaml ; pm2 save
